classes/schedule.php
=> set values to 0 if they do not exist

classes/admin.php
Do you think we need the `sanitize_text()` function? 
I almost think that `sanitize_text_field()` will do the trick and we can remove that function entirely.
per #11
=> Settings Sanitization

classes/admin.php, classes/salesforce_mapping.php, templates/admin/fieldmaps-add-edit-clone.php
This sanitizes any fieldmap data that wasn't already setup w/ sanitization
=> Sanitize Fieldmaps

readme.txt
We could put anything else that might need to go in [release.sh](https://github.com/MinnPost/object-sync-for-salesforce/blob/master/release.sh) in this pull request as well, but I think it's good already. But this readme is substantially edited.
=> update the readme.txt for the plugin directory

changelog.md, classes/wordpress.php, readme.txt
this will pass a blank space to both, allowing the insert to go on but not forcing any values
=> #103 allow empty title and/or content for inserting posts

classes/salesforce_mapping.php, templates/admin/fieldmaps-add-edit-clone.php
I believe this addresses #125.
=> 125 sync picklists

templates/admin/fieldmaps-add-edit-clone.php
This shows users a message about what the issue is with new meta fields.
Go to the add or edit fieldmap screen in the plugin settings. `/wp-admin/options-general.php?page=object-sync-salesforce-admin&tab=fieldmaps&method=add`
=> some help text about adding new meta fields

classes/admin.php, templates/admin/import-export.php, templates/admin/notice.php
This builds an interface for importing and exporting all plugin data:
1. Fieldmaps
2. Object maps
3. All plugin options
- Enter some data for all of those categories
- Export the data
- Import the data
I think it's a good idea to test with overwriting the data and without overwriting it. May need some error handling for that, too.
=> 38 allow exporting

classes/logging.php, classes/salesforce_pull.php
This adds a little more debug capability, and it also fixes a possible issue with other functionality while in debug mode.
Turn on debug mode. Let it run some queries.
=> 234 more debugging

classes/salesforce_mapping.php
This fixes #242.
Create a fieldmap like this.
Create a fieldmap where there's a meta field corresponding to the Salesforce Id.
Also test some fieldmaps that don't meet this criteria to make sure nothing is weird about them.
=> this seems to fix #242. at least when the push is async.

composer.json, composer.lock, vendor/composer/installed.json, vendor/prospress/action-scheduler/action-scheduler.php, vendor/prospress/action-scheduler/classes/ActionScheduler_Abstract_QueueRunner.php, vendor/prospress/action-scheduler/classes/ActionScheduler_AdminView.php, vendor/prospress/action-scheduler/classes/ActionScheduler_wcSystemStatus.php, vendor/prospress/action-scheduler/classes/ActionScheduler_wpPostStore.php, vendor/prospress/action-scheduler/tests/phpunit/runner/ActionScheduler_QueueRunner_Test.php
Update ActionScheduler to 2.2.1.
=> this fixes #247 by updating action scheduler

classes/salesforce_pull.php
This fixes #249 by making the checker work like this:
1. If the record is new, make sure the trigger is create.
2. Otherwise, the trigger can be update.
=> i believe this fixes the update checker

composer.json, composer.lock, vendor/composer/installed.json, vendor/prospress/action-scheduler/.gitattributes, vendor/prospress/action-scheduler/action-scheduler.php, vendor/prospress/action-scheduler/classes/ActionScheduler_AdminView.php, vendor/prospress/action-scheduler/classes/ActionScheduler_WPCLI_QueueRunner.php, vendor/prospress/action-scheduler/classes/ActionScheduler_wcSystemStatus.php, vendor/prospress/action-scheduler/classes/ActionScheduler_wpPostStore.php, vendor/prospress/action-scheduler/composer.json, vendor/prospress/action-scheduler/docs/_layouts/default.html, vendor/prospress/action-scheduler/docs/assets/css/style.scss, vendor/prospress/action-scheduler/license.txt
Update ActionScheduler to 2.2.4
=> fix #262. go ahead and update action-scheduler library

classes/logging.php
This fixes #281 by generating a probably unique slug in a more performant way.
- make sure logs generate the this fake slug
- make sure other posts don't
=> 281 fix log slug

classes/logging.php
This fixes #283 so the log prune settings change when the admin settings change.
- Change the admin log prune settings. The cron job should change.
- Save the settings without changing. The cron job should not change.
=> Fix log scheduling so it resets when the settings change

.travis.yml, composer.json, composer.lock
Hopefully it'll fix Travis so it will stop crashing. It uses a lot of the formatting from WooCommerce.
=> Stop Travis builds from failing

docs/initial-setup.md
Updates the documentation for creating a SalesForce app.
Follow the steps to create a new SalesForce application.
=> update SF setup

classes/salesforce_push.php
This uses the `acf/save_post` event to pass post data to the `post_actions` method that the plugin uses for admin saves. It should allow ACF forms to send front end data to Salesforce.
- Create and edit a post, and a custom post type record, on the front end using whatever functionality ACF uses. Make sure it goes to Salesforce as expected.
- Create and edit a post, and a custom post type record, with normal WordPress functionality on the admin side. Make sure nothing weird happens. Probably should test this both with and without the presence of ACF, just to be sure.
=> Add support for ACF forms that save posts on the front end. Thanks to WordPress user @grayzee for the request.

classes/class-object-sync-salesforce.php, classes/class-object-sync-sf-salesforce-pull.php, classes/class-object-sync-sf-salesforce-soap-partner.php
Fixes a possible miscall of the Soap library. This also calls a manual pull of a record after a merge occurs, which is how the code comments previously described it.
- enable SOAP
- do a merge in Salesforce that only the SOAP API can detect.
=> Improve reliability of SOAP API calls

classes/class-object-sync-sf-salesforce.php
This adds a `function_exists` check for `array_key_first`. If it's not there, it gets the first array item from `array_keys`.
- Use php < 7.3 (e.g. 7.0)
- Try to access the admin screen
=> For PHP versions below 7.3, add a quick check for `array_key_first`

templates/admin/fieldmaps-list.php
This fixes #433 by changing the fieldmap list table markup so that it behaves more like the post list table. This makes it easier to use it and also makes it resize better for different device sizes.
- look at the list of fieldmaps
=> Update the fieldmap list screen for better usability and device support.

templates/admin/import-export.php, templates/admin/mapping-errors.php, templates/admin/settings.php, templates/admin/status.php
This makes it easier to clear the plugin cache from different parts of the plugin admin section.
- see the clear cache link, click it
=> Adding more links to clear the plugin cache

changelog.md, changelog.txt, classes/class-object-sync-sf-pull-options.php, classes/class-object-sync-sf-salesforce-pull.php, classes/class-object-sync-sf-salesforce-push.php, classes/class-object-sync-sf-sync-transients.php, classes/class-object-sync-sf-transients.php, docs/all-developer-hooks.md, languages/object-sync-for-salesforce.pot
This finishes #414 by updating the transient settings so that they also support multiple fieldmaps on the same Salesforce object.
- the same way as #420.
=> Update transient settings to support multiple fieldmaps for the same Salesforce object.
