MinnPost/object-sync-for-salesforce

classes/salesforce_pull.php, classes/wordpress.php, docs/code/class-Salesforce_Pull.html, docs/code/class-Wordpress.html, docs/code/class-WordpressException.html, docs/code/source-class-Salesforce_Pull.html, docs/code/source-class-Wordpress.html, docs/code/source-class-WordpressException.html, docs/code/source-class-Wordpress_Salesforce_Schedule.html, docs/extending-wordpress.md
I believe this will resolve that #59 issue where we were creating `wp_salesforce_object_map` records when there's already a record.
~~We probably should create a demo using a hook to change the behavior, but this fixes the functionality.~~ I actually think that would be a bad design decision for users of the WordPress site, so I'm inclined to skip putting a hook in for this.
=> 59 upsert from salesforce bug

classes/activate.php
If php requirements aren't met, this will deactivate the plugin and use wp_die() to show an error message to the user.
=> Activation hook to check for php minimum requirements

classes/salesforce_pull.php
I don't think this entirely fixes #78 as there may still be rows with a wordpress id of 0 that never gets updated. I think maybe we need more logging to discover this. But this does allow new rows to be created, I think, and that was being prevented if there was one of these rows.
=> 78 pre existing mapping object

classes/salesforce.php
For #4, include the HTTP `errorCode` returned by the Salesforce API in the error message, since the second parameter on `new Exception` doesn't end up in the message: https://github.com/MinnPost/object-sync-for-salesforce/issues/4#issuecomment-302466891
=> Include error code in SalesforceException message when unable to get SF access token

classes/salesforce_mapping.php
When saving a new or edited mapping, if the mapping's Wordpress or Salesforce field choice is empty, do not save that mapping.
This is for #82, where API errors were being caused by mappings having no field, and thus generating invalid API calls to Salesforce. Not-saving the mapping means that the invalid mapping will not be used as part of the API call.
This has a side effect of cleaning empty field mappings from the admin without the need for the user to check the "delete" box for that row:
=> Remove bad mappings from the submitted mapping before saving

classes/wordpress.php
- In Wordpress::comment_upsert(), change 'notice' to 'error, because if, when creating/updating a WordPress comment, multiple WordPress comments exist for a given Salesforce ID, no comments will be updated.
- Change that error message to use `sprintf` so that we don't have to include a translation match for all possible combinations of status, count, key, value, and var_exported comments list.
If all comments for this Salesforce ID were updated, I would be in favor of it being a notice, but because nothing changes in the WordPress database, the comment upsert operation is failing to create or update any comments.
`var_export`ing the comments array so that they can be examined by someone reading the error log, so they can determine which/if to delete any of the comments.
Using sprintf …
=> Upgrade a notice to an error because it prevents items being saved

classes/admin.php
- one instance of esc_html to esc_attr; see https://github.com/MinnPost/object-sync-for-salesforce/commit/4e3526ba8ec875df2e5c9ac595b05cf16bd1dd3c#commitcomment-22265266
- a lot of `    ` to tab replacements for indentation. This doesn't do spaces-to-tabs replacements inside array element alignment spacing.
=> Mostly spaces-to-tabs fixes.

classes/admin.php, classes/salesforce_mapping.php, templates/admin/mapping-errors-delete.php, templates/admin/mapping-errors-edit.php, templates/admin/mapping-errors.php
This builds a basic interface for object map rows that failed to be fully created to map objects between the two systems, and have a temporary ID for either WordPress or Salesforce.
If any of these rows are present in the database, it creates a Mapping Errors tab at `/wp-admin/options-general.php?page=object-sync-salesforce-admin&tab=mapping_errors`.
For each row, it shows the WordPress ID, WordPress object type, Salesforce ID, and when it was created. Users are able to edit each row's WordPress and/or Salesforce ID, in case the data they need to map does actually exist, and are also able to delete each row individually in case they just want to let the plugin run again.
This should further solve the issues raised in #97, as it gives users a non SQL way to manage those error rows, on top …
=> 97 more zero id occurrences

classes/admin.php
I was reinstalling the plugin on an empty WP, and realized that it might be unclear that you have to set up a schedule before the plugin will do anything automatically. This could cause people to think the plugin should be doing things when it can't.
This pr adds admin notices for the various things the plugin requires to work, until they are created.
=> Set up admin notices for required settings if they don't exist

classes/salesforce_pull.php
Avoid repeatedly queueing SF objects by initializing rather than aggregating the queue before saving. This reduces memory use and DB size significantly.
Update the plugin pull sync timestamp for the data type after every successful record queue. This provides a correct starting point for the next pull to begin in case of a fatal error.
Attempt to mitigate #113 (if not completely resolve)
=> Mitigate fatal error while queueing large SF objects in a pull

classes/wordpress.php
See #115
Resolves issue where creating a new WordPress post from a modified existing SF Object loses all content fields, which have the method_modify wp_update_post rather than the expected wp_insert_post.
=> Check both insert & update to support creating a new WP post from a modified SF object

classes/admin.php, classes/deactivate.php
This fixes #129 by adding a checkbox to the Settings tab for deleting the plugin's data when it is uninstalled. It is not checked by default, but if it is checked it deletes the following things when the plugin is uninstalled:
1. The `object_sync_sf_field_map` and `object_sync_sf_object_map` database tables
2. Any scheduled tasks this plugin may have pending
3. The `wp_log` post type
4. The `configure_salesforce` capability. It also removes this capability from any roles that had it.
5. Any cached content related to this plugin
6. Any items in the `options` table that start with `object_sync_for_salesforce_`
- Install the plugin
- Save either value for the option
- Make sure it works as it should (either it should delete all the above data, or none of it)
=> 129 delete data on uninstall option

classes/salesforce_pull.php
Fixes #137
Setting the `'object_sync_for_salesforce_pull_last_sync_' . $type` timestamp after pull processing completes causes the sync to miss any SF changes that occurred after the sync query, while it processed records.
To resolve #113, the pull sync began also setting the last sync timestamp to the most recently processed record's pull_trigger_field value. Using those exclusively will resolve the race condition described in issue #137.
- click a button
- view the cat
- see the cat meow
=> Stop setting pull last sync timestamp after pull record processing completes

classes/salesforce_mapping.php, classes/wordpress.php
This provides a fix for #142. If a fieldmap is resaved, it will cause any dates coming from Salesforce that match core Wordpress date fields (ie post_date, post_modified, user_registered, etc.) to be used in the format WordPress expects.
1. Clear the plugin cache
2. Save a fieldmap that maps a Salesforce date field to one of the core WordPress date fields
3. Create or update data in Salesforce that matches this map. The data should be correctly saved in WordPress.
=> fix for 142

classes/admin.php, classes/salesforce_pull.php
This fixes the issue in #148, in which rows were sometimes created in WordPress from Salesforce create actions, even if only "Salesforce update" was an allowed trigger. This shouldn't happen.
1. Create a fieldmap like this:
2. Create data that matches it in Salesforce.
This data should not ever be created in Salesforce.
=> 148 update treated as upsert

classes/wordpress.php
This addresses the issue in #158 where a modified Salesforce Contact, which is not mapped to a user in WordPress but when the fieldmap does exist, would try to create a new user in WordPress but fail to add the email address to the email field.
This PR surprisingly just makes the `user_create` method behave more similarly to `post_create` with how it creates the array of content from the Salesforce data. I think this makes it less risky, and it may have just been overlooked previously.
The reported issue can be tested like this:
1. Find a Contact that exists in Salesforce, but is not mapped to a user in WordPress.
2. Update that Contact in Salesforce.
3. The plugin should create a new user in WordPress.
4. Make sure the new user has all the data it should have, especially the email …
=> 158 fix email field fails when creating new user from salesforce update

classes/salesforce_mapping.php
This fixes the issue where the key and prematch fields are ignored if their Salesforce status is not updateable, which breaks prematch.
- Create a new Contact in Salesforce
- Create a new user in WordPress
- Add a meta value to that user containing the Contact ID (field name: Id) from the new user in Salesforce
- Create a mapping for Users to Contacts with that meta key mapping to Contact ID, and some other fields mapped as well (just to be able to see the results), with at least WordPress update as a trigger. Make sure the meta->Contact ID fieldmap is marked as prematch and/or key and no other fields are marked as prematch or key
- Change the user's name
Instead of creating a new Contact in Salesforce, it should use the meta to perform an upsert on the existing and correct Contact …
=> 157 stop prematch and key from requiring updateable

classes/salesforce_push.php
For custom post types, the save_post_$object_type action does not use curly brackets.
fix issue where filter not executed when custom post type is updated/created
save a custom post type, see if it pushes to salesforce
=> removed curly brackets from add_action save_post_$object_type

classes/salesforce_mapping.php
Addresses #186 by bypassing the code that reformats a Salesforce field's value based on the field's data type when the value is NULL.
- Create a Salesforce setup that includes non-required date, int, text, and URL fields.
- Pull a record from Salesforce to WP for which those fields are empty or NULL.
- Confirm that they're all stored as NULLs in the WordPress database.
=> Don't coerce NULL values coming from Salesforce into other data types

classes/admin.php, classes/salesforce_mapping.php, templates/admin/mapping-errors.php
This provides checkboxes and a form to delete multiple object maps from the Mapping Errors tab of the admin interface. As such, it fixes #165.
- get some errors
- delete them via the checkboxes.
=> Delete multiple object map error rows

changelog.md, classes/salesforce.php, readme.txt
When Salesforce returns data from an API call, this PR allows developers to set whether they want json, the PHP array, or both to be returned.
=> allow developers to set return format value

classes/admin.php, classes/logging.php, classes/salesforce.php, classes/salesforce_pull.php, classes/salesforce_push.php
Fixes #220, in which pulling a batch of modified records in Salesforce could result in some of them being incorrectly skipped, if any of them were correctly not allowed to process.
1. Create a fieldmap that allows updated records to be pulled, but not created records.
2. Update a record that is already mapped in Salesforce so it should be updated in WordPress.
3. Create a new record in Salesforce that should not be created in WordPress.
All of these should behave as expected, if the fix works.
=> Fix pull records that are skipped when they shouldn't be

classes/salesforce_push.php, classes/wordpress.php
This fixes #224, which was preventing Salesforce records from being deleted when their corresponding WordPress records were deleted.
1. Delete a record in Salesforce that has a corresponding object map to a WordPress record.
2. Record is deleted in Salesforce.
=> 224 fix salesforce delete

classes/wordpress.php
See https://core.trac.wordpress.org/ticket/44293 and/or https://github.com/WordPress/WordPress/commit/655d44ffe813eb9a64e30a6339316338246e9efc
As of 5.1, WordPress rejects calls to `wp_new_user_notification()` whose third argument isn't either `'admin'`, `'user'`, `'both'`, or `''`. Previously, the value this plugin passes (`'admin user'`) was treated the same as `'both'`; but when it's running on WP 5.1, this plugin doesn't send any notifications at all. This PR changes the third argument to `'both'`.
- Pull a Salesforce record in such a way as to trigger the creation of a WordPress user
- Confirm that notifications are sent to both the site administrator's and the new user's email addresses
=> Make the call to `wp_new_user_notification()` compatible with WP 5.1

object-sync-for-salesforce.php
Fix activation hooks broken in 1.7.0. This fixes #239.
1. Deactivate the plugin, allowing it to clear its settings
2. Reactivate the plugin.
3. Find that permissions are correct, as well as other activation requirements.
=> fix activation bug

classes/admin.php, classes/salesforce_mapping.php, classes/salesforce_pull.php, object-sync-for-salesforce.php
This uses the SOAP api to add support for merging records. Thus it fixes #197.
- Merge two records in Salesforce where both are mapped to WordPress records.
- They should both be mapped to the same Salesforce record.
- Also delete a record from Salesforce that is not a merge, and it should still work.
=> Merge support

classes/wordpress.php
This fixes #252 by improving how error logs are created for WordPress update operations.
- Update some data in Salesforce
- It should only create an error when there's actually an error now.
=> Meta error logging

classes/admin.php, templates/admin/user-profile-salesforce-change.php, templates/admin/user-profile-salesforce-delete.php, templates/admin/user-profile-salesforce.php
- This fixes #251 by adding a delete option to the user profile Salesforce box. This allows object maps to be deleted in addition to being edited.
- delete an object map
- edit one too.
=> Delete object maps from user profile

classes/salesforce_mapping.php, classes/wordpress.php
This fixes #255 by providing basic support for saving Salesforce datetime fields in the patterns expected by The Event Calendar plugin. We need to make sure it doesn't conflict with ACF, CMB2, etc. methods of handling dates though.
- Install TEC plugin
- Map something from Salesforce to it. Good example is the default Event object.
- Install ACF/CMB2. Map some other event fields there and make sure there's no conflict.
=> Support datetime values for The Event Calendar

README.md, classes/activate.php, composer.json, composer.lock, phpcs.xml, readme.txt, vendor/composer/installed.json, vendor/prospress/action-scheduler/action-scheduler.php, vendor/prospress/action-scheduler/classes/ActionScheduler_Logger.php, vendor/prospress/action-scheduler/classes/ActionScheduler_wpPostStore.php, vendor/prospress/action-scheduler/docs/usage.md, vendor/prospress/action-scheduler/tests/phpunit/jobstore/ActionScheduler_wpPostStore_Test.php
- Updates included ActionScheduler to 2.2.5.
- Note: this also updates the minimum PHP version to 5.6.20, which is the minimum WordPress-supported version. It does this here because otherwise the composer install for developers (which includes WP) doesn't work.
- Set up a scheduled task. Make sure it runs as it should.
=> update actionscheduler to 2.2.5

README.md, docs/troubleshooting.md, readme.txt, templates/admin/fieldmaps-add-edit-clone.php
This fixes #271. Adds some documentation, and an inline link to the fieldmap add/edit screen, for permissions issues with object maps.
Probably the way to test this would be to create a Salesforce app with incorrect permissions and make sure the message shows up.
=> 271 object map permission issues

classes/salesforce_push.php, docs/extending-before-and-after-saving.md
Addresses the issues in #278
1) Update the documentation
2) Sets the $object_id to $salesforce_id
3) Copies the mapping object information into the synced object
1) Map a WordPress object to a Salesforce object
2) Add the example code to a custom plugin.
Modify the code to include a wp_mail call similar to:
wp_mail('your email', $op . ' - ' . $object_id, print_r($synced_object, true));
3) Create a new object in WordPress
4) Notice email has the new SF ID in the subject, and the mapping_object information is available in the $synced_object
=> Pull Success Updates

docs/all-developer-hooks.md
Fixes broken links in the All Developer Hooks Docs page
- Go to Docs page docs/all-developer-hooks.mdLinks 
- Four links fixed for Settings pages
- object_sync_for_salesforce_settings_tab
- documentation: add a settings tab
- object_sync_for_salesforce_settings_tab_include_settings
- documentation: change the template
- object_sync_for_salesforce_settings_tab_content_before 
- documentation: adding settings 
- object_sync_for_salesforce_settings_tab_content_after 
- documentation: adding settings
Two links fixed to main class
- object_sync_for_salesforce_modify_schedulable_classes
-  code: object-sync-for-salesforce.php
- object_sync_for_salesforce_select_library
- code: object-sync-for-salesforce.php
=> Fix docs links in All Developer Hooks

classes/salesforce_push.php, docs/extending-before-and-after-saving.md
This makes the `object_sync_for_salesforce_push_success` hook have consistent parameters across all the places where it's called, and updates the documentation to match it. This is backward compatible as far as the docs are concerned. It also applies the #278 order on all the instances of this hook.
=> Unify push success hook parameters

classes/admin.php, classes/logging.php
This adds a settings field to the Log settings tab. If present, this is what the log prune task will use to tell how many log entries to clear. This fixes #294.
- change the settings for log clearing
- the plugin should clear that many entries
=> Provide an optional setting for how many log entries to clear

classes/wordpress.php
This fixes an error logging issue - and possibly other problems - when a Salesforce Picklist field is mapped to a WordPress field and is unable to save. The error logging wasn't working.
This fixes #296.
=> Fix picklist error logging

classes/admin.php
Add parameter counts to calls to add_action in admin.php
Also add a parameter to push_to_salesforce which can force the method to return rather than print its output.
It adds parameter counts to the actions defined in admin.php
call  do_action('wp_ajax_push_to_salesforce', 'user', $userId)
=> Fix calls to add_action in admin.php

classes/wordpress.php, docs/extending-mapping-options.md
Sending the current object type to the WordPress action so we know what type is currently being used while sending it to Salesforce. This allows us to alter WordPress data by current object.
=> Adding object type to wordpress_object_data filter

classes/salesforce_push.php
Fix #311 by making the log entry a notice instead of an error if it occurs because of the fieldmap's log settings.
=> When a fieldmap doesn't allow an operation, log it as a notice instead of an error

classes/salesforce.php, classes/salesforce_mapping.php, classes/salesforce_pull.php, classes/salesforce_push.php, classes/wordpress.php
This edits the various log entries we create so they use the already existing status variable. It makes it easier to change, see what's going on, removes some unneeded duplication, etc.
=> use the log entry status variable in the title of all the log entries

classes/salesforce_pull.php, docs/extending-pull.md
Fix #314 by changing the `object_sync_for_salesforce_pull_query_modify` filter to:
1. Correct documentation and code comments that match what the filter is actually doing.
2. Ensure that the SOQL object properties which are arrays are always unique.
=> Fix the object_sync_for_salesforce_pull_query_modify filter to prevent redundant elements

classes/salesforce_mapping.php
As indicated in #320, WordPress stores capabilities in a certain way, and this doesn't match how Salesforce stores picklist values. I think this PR translates for that field's usage, both coming from and going to Salesforce.
- Install any plugin that supports the WP roles API (members plugin, multiple-roles plugin, etc.)
- Map users to something in Salesforce
- Give users multiple roles in WordPress
- Give users multiple roles in Salesforce
=> If the WordPress field is wp_capabilities, we can treat it as WordPress expects it

classes/admin.php
This closes #325. It hides all menu items except Settings and Authorize if the user has not authorized with Salesforce.
Here's how the menu visibility works:
1. If user has not filled in the credentials, only show Settings.
2. If user has filled in credentials but has not authorized the app in Salesforce, only show Settings and Authorize.
3. If they've actually authorized with Salesforce, show all the available items.
- install the plugin
- fill in the credentials but don't authorize
- authorize
=> Hide admin menu items before authorizing with Salesforce

classes/activate.php, classes/admin.php, classes/salesforce_pull.php
In WordPress 5.3, `current_time( `timestamp' )` is no longer recommended. Rather, they say we should use `time()` to get timestamps. This PR fixes #342.
=> For WordPress 5.3 compatibility, replace `current_time( 'timestamp' )` with `time()`

templates/admin/mapping-errors.php
This fixes #348. It changes the markup on the mapping error table so it can use the existing WP functionality to check all the boxes.
- Have multiple error rows
- Check the box to select all of them
=> Add a checkbox to delete all mapping errors

classes/salesforce_mapping.php, classes/salesforce_push.php
This fixes #350 by checking for a WordPress ID before creating or updating an object map. If it does not have that value, it creates an error log.
I'm a little unsure how to test this yet. It's not exactly clear to me what causes this error to happen.
=> Check for a WordPress ID before creating an object map.

classes/admin.php, classes/salesforce_mapping.php, templates/admin/mapping-errors.php
Add a settings field to the mapping errors tab for how many errors it should show per page. Defaults to 50.
- get more than one mapping error
- change the settings to make sure it paginates correctly.
=> Add a settings field for mapping errors per page. Defaults to 50.

classes/wordpress.php
This fixes #357. When running a WordPress action (`user_register`, etc.), this makes sure that the ID represents a WordPress object. If it fails to create a user without causing a WP error, for example, this will keep it from trying to create a Salesforce record.
I found this issue when testing spam users. The user wasn't being created, but it also wasn't flagging an error so the plugin was trying to move on with it. This fixes that.
=> Make sure a WordPress record is an object before loading its data and processing it

classes/admin.php
I read through all the issues related to [#98](https://github.com/MinnPost/object-sync-for-salesforce/issues/98), and even though it seemed like you should be able to technically sync objects I only saw them saved to the `wp_object_sync_sf_object_map` table. This change seems to at least work for me for syncing the data in advance. I am sure it can be improved on.
```json
{
"object_maps": [
{
"wordpress_object": "user",
"salesforce_id": "0035w000034dIMuAAA"
}
]
}
```
- Makes it so that posts, users, etc are created along with the object_map on import. 
- create a JSON file like the following
```json
{
"object_maps": [
{
"object_type": "Contact",
"salesforce_id": "0035w000034dIMuAAA"
}
]
}
```
- use the admin UI to import the file
=> create object as well as object_map in import_json_file

classes/salesforce_push.php
In #370, when a filter prevents a record from being pushed to Salesforce, there can be an unnecessary PHP error.
1. Try to push a record that, based on the filter, is not allowed to be pushed.
2. Check the server error logs.
3. Check the WordPress logs to make sure it is correctly logged.
=> Prevent PHP error when a filter does not allow a record to be pushed to Salesforce.

classes/salesforce_push.php
This fixes #373. In 1.9.4, a strict check was incorrectly added to an array when the value is a bit value, so the strict check would fail.
- This affects the `push_allowed` flag.
=> Remove a strict check that was incorrectly added. Thanks to WordPress user @afgarcia86 for the report.

classes/admin.php, templates/admin/fieldmaps-add-edit-clone.php
When adding a new field to a fieldmap, the Salesforce field dropdown list wasn't respecting the plugin settings value for whether to show the API Name or Label value for the Salesforce field. This fixes #377.
1. Create a Fieldmap with some fields and save
2. Edit the Fieldmap and add a new field
3. Compare the list of options for the 'Salesforce Field' for an existing field and the one you just added.
=> Fix the Salesforce field dropdown so it respects the API Name/Label settings value. Thanks to @CodeZeno.

docs/mapping.md
There are some cases where the plugin detects what kind of field it is dealing with and formats the data accordingly. This documents which WordPress field types the plugin handles by default, which Salesforce field types it handles, and how it handles them.
=> Document how the plugin handles fields with different data types #376

classes/salesforce_pull.php
If a fieldmap has allowed record types, use them to constrain the SOQL query that is used to pull updated records from Salesforce. This should fix #383.
- I think make fieldmaps that do and that do not use "allowed record types" and make sure it works in both cases.
=> If a fieldmap has allowed record types, use them to constrain the SOQL sent to Salesforce

classes/class-object-sync-sf-activate.php, classes/class-object-sync-sf-admin.php, classes/class-object-sync-sf-deactivate.php, classes/class-object-sync-sf-logging.php, classes/class-object-sync-sf-mapping.php, classes/class-object-sync-sf-salesforce-pull.php, classes/class-object-sync-sf-salesforce-push.php, classes/class-object-sync-sf-wordpress-transient.php
This fixes #375 by converting the bit flags that came over from Drupal into strings that are more readable, and can be used in strict comparisons as well.
- make sure the log settings and the fieldmap settings show the correct values after switching to version 2.0.0 of the plugin
- make sure the push and pull events work the way they should for create, update, delete
- make sure the log entries are stored correctly
=> Convert bit flags to more readable strings

changelog.md, classes/class-object-sync-sf-admin.php, classes/class-object-sync-sf-mapping.php, classes/class-object-sync-sf-salesforce-pull.php, classes/class-object-sync-sf-salesforce-push.php
-  `add_deprecated_actions` in  `Object_Sync_Sf_Admin`
- `get_wp_sf_object_fields` in `Object_Sync_Sf_Admin`
- `load_by_wordpress` in `Object_Sync_Sf_Mapping`
- `load_by_salesforce` in `Object_Sync_Sf_Mapping`
`get_object_maps` from the `Object_Sync_Sf_Mapping` class was previously deprecated, but was still being called in various places. It no longer is.
This closes #336.
- make sure push and pull requests run as expected
- make sure fieldmap adding/editing works as expected
=> Remove deprecated methods from prior to version 2.0.0.

classes/class-object-sync-sf-mapping.php, classes/class-object-sync-sf-salesforce-pull.php, classes/class-object-sync-sf-salesforce-push.php, classes/class-object-sync-sf-salesforce.php, classes/class-object-sync-sf-wordpress.php
This change fixes #389. it combines two debug messages that could be created on Salesforce API calls, and cleans up the message content in the combined message.
- turn on debug mode
- run a call that does include a SOQL query
- run a call that does not include a SOQL query
=> Refine debug log messages on Salesforce API calls

templates/admin/fieldmaps-add-edit-clone.php
This fixes #415 by only disabling already mapped fields when the setting is enabled, as it should be.
- Ensure the new "Prevent Duplicate Field Mapping?" option is unchecked.
- Add/edit a Field Mapping.
- Map some WordPress fields to Salesforce.
- Save & reload the Field Mapping.
- Fields already mapped should be selectable.
- Ensure the new "Prevent Duplicate Field Mapping?" option is checked.
- Add/edit a Field Mapping.
- Map some WordPress fields to Salesforce.
- Save & reload the Field Mapping.
- Fields already mapped should not be selectable.
=> Duplicate mapping of fields was prevented when it shouldn't be. Thanks to @timnolte for the report.

classes/class-object-sync-sf-salesforce-pull.php, classes/class-object-sync-sf-wordpress.php
When the plugin tries to update a record in WordPress and it fails, we've previously only logged the error message and the WordPress ID. This adds to that log message the Salesforce object ID and the parameters the plugin was trying to update.
- one way would be to successfully sync two records and then delete the WordPress record without deleting the object map from the database.
- The other is to code a value into `$result['errors']` in the WordPress class right before it creates this log entry.
=> Improve the log message when an update to a WordPress record fails

classes/class-object-sync-sf-mapping.php
This fixes #418.
>  After upgrading to the 2.x version of the plugin I have found that specifically in the case where I have multiple mappings for a Salesforce Object to a WordPress Object, because of multiple Salesforce record Types, that when those records from Salesforce are being processed the resulting WordPress Post Type ends up being set as `post`, when logs and debug processing indicate that it should have created a Custom Post Type (e.g. `sf_industry_location`). I verified that reverting back to the 1.9.9 version of the plugin restored the proper WordPress Post Type is created.
- Setup 2 or more Fieldmappings to the same WordPress Custom Post Type against a Salesforce Object with multiple record Types. (1 mapping per record type.)
- Modify or create one of those records in …
=> Fix missing Record Type when pulled from Salesforce. Thanks to @timnolte for the report.

classes/class-object-sync-sf-mapping.php, classes/class-object-sync-sf-salesforce-pull.php, classes/class-object-sync-sf-salesforce-push.php
This completes work on #362. In a previous version, we added a lock to Salesforce fields that cannot be updated. In this version, we create a debug log entry if the plugin tries to run a push or pull on a specific record, but in the end none of the parameters can be saved.
- turn on debug mode/logging
- map only Salesforce fields that are not updateable
- try to update them
=> Create a log entry if the plugin tries to sync a record but no parameters are eligible. Thanks to @OfficeBureau for the report.

docs/accessing-salesforce-object.md, docs/all-developer-hooks.md
As indicated in #425, the filename URLs were not updated in the documentation when version 2.0.0 was released. This updates those references so they correctly point to the renamed files. As such this fixes #425.
- click around in the documentation, especially on the all-developer-hooks.md file.
=> Update URLs in the documentation that point to plugin PHP files to match their v2.0.0 filenames

classes/class-object-sync-sf-salesforce-pull.php, docs/all-developer-hooks.md, docs/extending-pull.md
This adds a new filter for developers, `object_sync_for_salesforce_pull_query_string_modify`, which allows them to modify the entire SOQL string by hand before it is sent to the Salesforce API. This fixes #428.
- write a SOQL string query that works and use it in a plugin or theme
=> Add a filter to allow developers to edit the whole SOQL string. Thanks to WordPress user @jellypixel.

object-sync-for-salesforce.php
When the plugin is newly installed, it suggests a default version of the Salesforce REST API. This updates that value to 53.0, the current version.
=> Change the default Salesforce REST API version to 53.0.

classes/class-object-sync-sf-salesforce-push.php
When adding a user via the Ultimate Members plugin, prevent an incorrect error message log by adding the user ID value to the passed data. This fixes #439.
- add a new mapped user with and without Ultimate Members being installed.
=> When adding a user via the Ultimate Members plugin, prevent an incorrect error message log by adding the user ID value to the passed data.

classes/class-object-sync-sf-pull-options.php, classes/class-object-sync-sf-sync-transients.php
This removes the arrow functions because, as stated by @trohrer:
> Unfortunately ofrayechiel is correct. When Zend added arrow functions in 7.4, it now throws errors in the syntax parser of existing, older versions of PHP.
- run PHP version 7.3 or earlier
=> Remove arrow functions that are only supported in PHP 7.4. Thanks to WordPress users @ofrayechiel and @trohrer for the report.

templates/admin/fieldmaps-add-edit-clone.php
In addition to preventing the PHP notice in the server logs, this matches the normal pattern for this template. Normally those default values are empty, but in this case it makes sense for the default to have a value. This fixes #456.
- create a new fieldmap
- see that the error logs aren't affected.
=> When creating a new fieldmap, set a default status of "active" to prevent a PHP notice.

README.md, changelog.md, changelog.txt, classes/class-object-sync-salesforce.php, classes/class-object-sync-sf-admin.php, classes/class-object-sync-sf-salesforce.php, docs/adding-settings.md, docs/all-developer-hooks.md, object-sync-for-salesforce.php, templates/admin/status.php
This fixes #458 by removing the requirement to set the Salesforce REST API version from the interface in favor of a plugin-wide setting. This setting allows us to track Salesforce API releases within the plugin itself rather than putting that responsibility onto users.
For backward-compatibility, for the time being the plugin will use previously-provided settings (both as config values and as `wp_options` values) and show a notice to users if they are using one of those settings.
For future developer flexibility, this also adds a developer hook in case developers want to set their own version of the API.
- use the plugin without any previously set version: it should use the value from the object-sync-for-salesforce.php file (currently 55.0).
- use the plugin with a previously set config …
=> Remove the requirement to set the Salesforce REST API version from the interface in favor of a plugin-wide setting.

classes/class-object-sync-sf-salesforce-pull.php
This fixes #466. The `pull_merge_last` option value is supposed to be fieldmap-specific, ex `object_sync_for_salesforce_pull_merge_last_Contact_2` instead of `object_sync_for_salesforce_pull_merge_last_Contact`. This fixes the problem with the SOQL queries that are used to detect merges.
- enable merging on a fieldmap
- merge some records that apply to that fieldmap
- see that they are merged
=> Fix the `pull_merge_last` option value that is used on merge operations

classes/class-object-sync-sf-admin.php, classes/class-object-sync-sf-mapping.php, classes/class-object-sync-sf-salesforce-pull.php, classes/class-object-sync-sf-salesforce-push.php, classes/class-object-sync-sf-salesforce.php, classes/class-object-sync-sf-wordpress.php
This is a start at addressing #459. All it really does is make all the log class calls correct and less redundant. It should not result in any behavior changes.
- make sure no plugin behaviors are different.
=> Start to clean up log code. Because of old code that was never updated, our log method was called 1) incorrectly, and 2) in an overly redundant way.

classes/class-object-sync-sf-admin.php, templates/admin/status.php
In some cases when the API authorization has expired, the plugin does not detect that this has happened and so it still tries to load the demo 100 contacts from Salesforce. This pull request checks to make sure there is a success code on that API call, and that there are `records` returned.
- check the Authorize page in a scenario when the connection has expired
- check it when the connection is working properly
=> Add an error handler on the Authorize screen in case no data is returned by the demo API call.

classes/class-object-sync-sf-admin.php, classes/class-object-sync-sf-logging.php, docs/adding-settings.md, docs/initial-setup.md, docs/troubleshooting.md
Previously, when the plugin was in debug mode, users also had to enable debug log messages. This is an unnecessary amount of configuration. Now, enabling debug mode enables all debug logging, regardless of the other log settings.
- enable Debug Mode; watch for log entries
- disable Debug Mode; the plugin should respect the other log settings for the plugin.
=> Setting the plugin's Debug Mode enables debug logging, regardless of other log settings.

classes/class-object-sync-sf-salesforce-pull.php
In some cases, an empty error would be flagged as an error instead of as a success. This fixes #474.
=> Fixes an issue where an error was incorrectly flagged upon a successful sync

classes/class-object-sync-sf-wordpress.php
Fixes undefined WP_Query method bug #484 
1. Setup a mapping that Prematches on a metavalue for a metakey ( e.g. "salesforce_id" ).
2. Create a post and add that postmeta key.
3. Initiate a sync with a Salesforce record that has a value that matches the metavalue of a pre-existing post.
4. Check that the new row created in `wp_2020_object_sync_sf_object_map` has the same post_id as the pre-existing post's ID, and a new/duplicate post is not created.
=>  Fix undefined WP_Query method preventing prematch

classes/class-object-sync-sf-wordpress.php
The fix from #485 should also apply to attachment prematching since attachments use WP_Query. Thanks again to @MannyAdumbire.
This also adds comments to the other match methods to specify which object is being used and what method it contains.
=>  Fix undefined WP_Query method preventing prematch on attachments.

classes/class-object-sync-sf-wordpress.php
Added lines 209-230 to check for WP Multisite installation. 
If it's a Multisite, then the 'user' object will be accessed using the 'wpdb->base_prefix' because the 'user' table is the same across all sites and just 'wpdb->prefix' does not work.
If it's not a Multisite, then the previous code executes.
Adds WP Multisite compatibility for the 'user' object
Install the plugin on WP Multisite installation. 
Create a Fieldmap with the 'user' WordPress object (current version of plugin doesn't work at this point)
=> Add Multisite support for user data in WordPress.

classes/class-object-sync-sf-mapping.php
This fixes #500 by using `$this->wpdb->prefix . 'capabilities'` instead of `wp_capabilities`.
- Map a capabilities field with a custom prefix
- Map a capabilities field without a custom prefix
=> Use the WordPress install's database prefix with the capabilities field. Thanks to WordPress user @dhartendorp for the report.

classes/class-object-sync-sf-wordpress.php, templates/admin/mapping-errors-edit.php, templates/admin/mapping-errors.php
When the Mapping Errors tab is present, provide direct links to edit the WordPress and/or Salesforce record, depending on which ones exist. This applies both to the list of all errors, and to the individual error record. This closes #479.
- generate some errors
- see the edit links
=> Add links to edit the WordPress and/or Salesforce record on the Mapping Errors tab

classes/class-object-sync-sf-salesforce.php
This PR adds a filter to the `http_request()` function in class `Object_Sync_Sf_Salesforce` to allow short-circuiting the API call and response.
The goal of the PR is to help create a tighter integration with WP Fusion (https://github.com/verygoodplugins/wp-fusion-lite/ and https://wpfusion.com/).
The logic follows what already exists in WP core, for example with `update_metadata()`: https://github.com/WordPress/WordPress/blob/master/wp-includes/meta.php#L233
With this filter in place, we will be able to:
- Route outgoing API calls through WP Fusion (and the WordPress HTTP API / `wp_remote_request()`)
- Use WP Fusion's built in error handling, logging, and token refresh capabilities for Object Sync API calls
- Detect potential data collision (for example if WP Fusion is about to operate …
=> Added filter to short-circuit API calls to Salesforce

classes/class-object-sync-sf-logging.php, classes/class-object-sync-sf-mapping.php
Load the plugin and view the error log. This PR will clean up the deprecation notices for dynamic properties. There are still some other deprecations for other things, but I wanted to limit the scope of this PR and also make sure I didn't break anything :)
=> Fix php 8.2 dynamic properties

classes/class-object-sync-sf-admin.php
Replaces `FILTER_SANITIZE_STRING` with either `FILTER_SANITIZE_SPECIAL_CHARS` or `FILTER_UNSAFE_RAW`, depending on what the rest of the code is doing.
- save plugin settings (especially fieldmaps)
- save some data in push and pull operations
=> Remove all uses of FILTER_SANITIZE_STRING, since it's deprecated in newer PHP versions.

classes/class-object-sync-sf-logging.php
In this particular case, `$schedule_number` must be a number because in [line 393](https://github.com/MinnPost/object-sync-for-salesforce/blob/master/classes/class-object-sync-sf-logging.php#L393) it is being multiplied. I'm not sure if it is a PHP8 thing, but you cannot multiple an int ($seconds) by a string (empty or otherwise). `$schedule_number` must be a positive int, just casting isn't enough, `absint` should cover it.
I only noticed this on a blank WP install, if you turn logging on it'll throw a fatal as no schedules have ever been set.
=> Prevent error on blank WordPress install caused by a string instead of an integer. Thanks to GitHub user @federicojacobi for the pull request.

classes/class-object-sync-sf-mapping.php, classes/class-object-sync-sf-queue.php
In newer versions of PHP, the log entry `Using ${var} in strings is deprecated` appears. This fixes at least some of the places where this would happen.
=> Fix a couple of deprecated warnings that appear in logs in newer php versions

classes/class-object-sync-sf-salesforce-pull.php
This PR fixes the issue #541 by changing how the offset is calculated to avoid losing record updates when pulling data from SalesForce.  I made the following changes:
- Added a a third param to get_pull_query function: when true the offset for the new query is not calculated. This way when calling get_pull_query for the first time during the object_sync_for_salesforce_pull_check_records action the offset is not added two times.  
- increment_current_type_datetime is called when the does_next_offset_have_results variable is true. I made this change following this logic:
1. after writing the items to the queue, another query is sent with an additional offset to check if there are results, using the current LastModifiedDate.
2. If there are results, store in db the LastModifiedDate of the …
=> Fix offset calculation to avoid losing offset record updates

classes/class-object-sync-sf-logging.php, classes/class-object-sync-sf-queue.php
When setting up the plugin, WordPress can encounter errors saving the schedule settings. Additionally, it sometimes flags an error when the Log Settings are initially saved. This fixes both occurrences.
- do a new install of the plugin
- see that errors do not appear in the logs
- see that scheduled pull tasks still run as they should after the schedule settings are saved
=> Prevent errors that can occur when saving log settings and schedule settings on initial plugin setup
